### ISSUE TITLE
CtrlPLocate 実行時にエラー発生

### ISSUE THREAD

**Issue by hokorobi** [ompugao/ctrlp-locate#4]
8af5a76 から 665e44e にしたところ CtrlPLocate を実行すると
以下の様なエラーが出るようになってしまいました。
vim74-kaoriya-win64-20150830

function <SNR>92_GetFunc の処理中にエラーが検出されました:
行    2:
E700: 未知の関数です: <SNR>51_getinput

**Comment by ompugao** [comment]
vim-airlineかなにかをお使いでしょうか？
別のプラグインに"ctrlp.vim"というファイルがあって、
読み込み順がうっかり変わるか何かしたせいで
ctrlp.vimのスクリプト内関数s:getinputが取ってこれないようになっているのだと思います
:scriptnames して51番目のファイルを見てみてください
（なぜ 5a9f831cafff40730d8e4604222fbe09f86e0006 の変更でそのようなことが起こるのかよくわかりません…）

bugfixをしようかとも思ったのですが、
そのようなスクリプト内関数を無理やり呼ぶ行為のをやめたくなったので、
新たに[use_matcher](https://github.com/ompugao/ctrlp-locate/tree/use_matcher) branchに作りましたのでご査収ください
もしこれまでの挙動の方が好ましいようであれば v0.5 8af5a76 を引き続きご利用ください。
気が向いたらbugfixをしようかと思います（たぶんしないやつ）

**Comment by ompugao** [comment]
もはやissueに関係ないですが、そのうちuse_matcher branchをmasterにmergeしようかと思ってます

**Comment by hokorobi** [comment]
51番目のファイルは ctrlp.vim の ctrlp.vim でした。
use_matcher branch ではエラーは出なくなりました。
ありがとうございます！

**Comment by ompugao** [comment]
よかったです
ついでにmasterにmergeしました

**Comment by hokorobi** [comment]
さっそく master に切り替えました。
