### ISSUE TITLE
g:ctrlp_key_loop = 1 の場合に文字を入力するだけでは検索結果が表示されない

### ISSUE THREAD

**Issue by hokorobi** [ompugao/ctrlp-locate#5]
g:ctrlp_key_loop = 0 で回避できるので困ってはいませんが、g:ctrlp_key_loop = 1 の場合に文字を入力するだけでは検索結果が表示されず、BS で文字を一文字消したりすると検索結果が表示されました。

ec4bca3
vim74-kaoriya-win64-20150830

**Comment by ompugao** [comment]
https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L239
によるとlet g:ctrlp_key_loop=1すると強制的にlazy_updateはoffになるようにコーディングされているので、vimおよびctrlp.vimの仕様なのではないかと思います

**Comment by hokorobi** [comment]
修正ありがとうございます、g:ctrlp_key_loop = 1 でも期待通りの動きになりました。
